version: '3.8'
services:
  app:
    build: ./back-end
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desires-app-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"